name: Feature Request
description: Suggest a new feature or enhancement for EconNews
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checks
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have read the [CONTRIBUTING.md](../../CONTRIBUTING.md) guide
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is this feature for?
      options:
        - Frontend (Next.js)
        - Backend (FastAPI)
        - API
        - Database (Firestore)
        - SEO/AEO
        - UI/UX
        - Documentation
        - DevOps/CI-CD
        - Other
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New functionality
        - Enhancement to existing feature
        - Performance improvement
        - Developer experience
        - Security improvement
        - Accessibility improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also considered...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how this feature would be used
      placeholder: |
        1. User wants to...
        2. User goes to...
        3. User expects...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, wireframes, or examples from other apps
      placeholder: Drag and drop images here or paste URLs

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my use of the app
        - High - Very important
        - Medium - Would be nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: checkboxes
    id: languages
    attributes:
      label: Language Support
      description: Should this feature support multiple languages?
      options:
        - label: This feature should support all 15 languages
        - label: This is language-specific (specify in additional context)
        - label: Not applicable

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas on how to implement this, please share
      placeholder: This could be implemented by...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request
      placeholder: Any additional information...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would be willing to submit a PR for this feature
        - label: I can help with testing
        - label: I can help with documentation
